// src/utils/scrabbleWords.ts
export const scrabbleWords = new Set([
    // 2-letter words
'AA','AB','AD','AE','AG','AH','AI','AL','AM','AN','AR','AS','AT','AW','AX','AY','AO','BA','BE','BI','BO','BY','DA','DE','DO','ED','EF','EH','EL','EM','EN','ER','ES','ET','EW','EX','FA','FE','GI','GO','HA','HE','HI','HM','HO','ID','IF','IN','IS','IT','JO','KA','KI','LA','LI','LO','MA','ME','MI','MM','MO','MU','MY','NA','NE','NO','NU','OD','OE','OF','OH','OI','OK','OM','ON','OP','OR','OS','OW','OX','OY','PA','PE','PI','PO','QI','RE','SH','SI','SO','TA','TE','TI','TO','UH','UM','UN','UP','US','UT','WE','WO','XI','XU','YA','YE','YO','ZA','CH','DI','EA','EE','FY','GU','IO','JA','KO','KY','NY','OB','OO','OU','ST','UG','UR','YU','ZE','ZO',
  
    // 3-letter words
    'AAL', 'AAS', 'ABA', 'ABB', 'ABO', 'ABS', 'ABY', 'ACE', 'ACT', 'ADD', 'ADO', 'ADS', 'ADZ', 'AFF', 
    'AFT', 'AGA', 'AGE', 'AGO', 'AGS', 'AHA', 'AHI', 'AHS', 'AID', 'AIL', 'AIM', 'AIN', 'AIR', 'AIS', 
    'AIT', 'ALA', 'ALB', 'ALE', 'ALF', 'ALL', 'ALM', 'ALP', 'ALS', 'ALT', 'AMA', 'AMI', 'AMP', 'AMU', 
    'ANA', 'AND', 'ANE', 'ANI', 'ANN', 'ANT', 'ANY', 'APE', 'APO', 'APP', 'APT', 'ARB', 'ARC', 'ARE', 
    'ARF', 'ARK', 'ARM', 'ARS', 'ART', 'ASH', 'ASK', 'ASP', 'ASS', 'ATE', 'ATT', 'AUK', 'AVA', 'AVE', 
    'AVO', 'AWA', 'AWE', 'AWL', 'AWN', 'AXE', 'AYE', 'AYS', 'AYU', 'AZO', 'BAD', 'BAG', 'BAH', 'BAL', 
    'BAM', 'BAN', 'BAP', 'BAR', 'BAS', 'BAT', 'BAY', 'BED', 'BEE', 'BEG', 'BEL', 'BEN', 'BES', 'BET', 
    'BEY', 'BIB', 'BID', 'BIG', 'BIN', 'BIO', 'BIS', 'BIT', 'BOA', 'BOB', 'BOD', 'BOG', 'BOO', 'BOP', 
    'BOS', 'BOT', 'BOW', 'BOX', 'BOY', 'BRA', 'BRO', 'BRR', 'BUB', 'BUD', 'BUG', 'BUM', 'BUN', 'BUS', 
    'BUT', 'BUY', 'BYE', 'BYS', 'CAB', 'CAD', 'CAM', 'CAN', 'CAP', 'CAR', 'CAT', 'CAW', 'CAY', 'COB', 
    'COD', 'COG', 'COL', 'CON', 'COO', 'COP', 'COR', 'COT', 'COW', 'COX', 'COY', 'CRY', 'CUB', 'CUE', 
    'CUM', 'CUP', 'CUR', 'CUT', 'CWM', 'DAB', 'DAD', 'DAH', 'DAM', 'DAN', 'DAP', 'DAR', 'DAY', 'DEB', 
    'DEE', 'DEF', 'DEL', 'DEN', 'DEV', 'DEW', 'DEX', 'DIB', 'DID', 'DIE', 'DIG', 'DIM', 'DIN', 'DIP', 
    'DIS', 'DIT', 'DOC', 'DOE', 'DOG', 'DOL', 'DOM', 'DON', 'DOO', 'DOR', 'DOS', 'DOT', 'DOW', 'DRY', 
    'DUB', 'DUD', 'DUE', 'DUG', 'DUI', 'DUN', 'DUO', 'DUD', 'DUH', 'DUX', 'DYE', 'EAR', 'EAT', 'EAU', 
    'EBB', 'EDS', 'EEK', 'EEL', 'EFT', 'EGG', 'EGO', 'ELF', 'ELM', 'ELS', 'EME', 'EMS', 'EMU', 'END', 
    'ENG', 'ENS', 'EON', 'ERA', 'ERE', 'ERG', 'ERN', 'ERR', 'ERS', 'ESS', 'ETA', 'ETH', 'EVE', 'EWE', 
    'EYE', 'FAB', 'FAD', 'FAG', 'FAN', 'FAR', 'FAS', 'FAT', 'FAX', 'FAY', 'FED', 'FEE', 'FEH', 'FEM', 
    'FEN', 'FER', 'FET', 'FEY', 'FEZ', 'FIB', 'FID', 'FIE', 'FIG', 'FIN', 'FIR', 'FIT', 'FIX', 'FLU', 
    'FLY', 'FOB', 'FOE', 'FOG', 'FOH', 'FON', 'FOP', 'FOR', 'FOU', 'FOX', 'FOY', 'FRO', 'FRY', 'FUB', 
    'FUD', 'FUG', 'FUN', 'FUR', 'GAD', 'GAG', 'GAL', 'GAM', 'GAP', 'GAR', 'GAS', 'GAT', 'GAY', 'GED', 
    'GEE', 'GEL', 'GEM', 'GEN', 'GET', 'GEY', 'GIB', 'GID', 'GIG', 'GIN', 'GIP', 'GIT', 'GOB', 'GOD', 
    'GOO', 'GOR', 'GOS', 'GOT', 'GOX', 'GUL', 'GUM', 'GUN', 'GUT', 'GUY', 'GYM', 'GYP', 'HAD', 'HAE', 
    'HAG', 'HAH', 'HAM', 'HAP', 'HAS', 'HAT', 'HAW', 'HAY', 'HEH', 'HEM', 'HEN', 'HEP', 'HER', 'HES', 
    'HET', 'HEW', 'HEX', 'HEY', 'HIC', 'HID', 'HIE', 'HIM', 'HIN', 'HIP', 'HIS', 'HIT', 'HMM', 'HOB', 
    'HOD', 'HOE', 'HOG', 'HON', 'HOP', 'HOT', 'HOW', 'HOY', 'HUB', 'HUE', 'HUG', 'HUM', 'HUN', 'HUP', 
    'HUT', 'ICE', 'ICK', 'ICY', 'IDS', 'IFF', 'IFS', 'ILK', 'ILL', 'IMP', 'INK', 'INN', 'INS', 'ION', 
    'ITS', 'IVY', 'JAB', 'JAG', 'JAM', 'JAR', 'JAW', 'JAY', 'JEE', 'JET', 'JEU', 'JEW', 'JIB', 'JIG', 
    'JIN', 'JOB', 'JOE', 'JOG', 'JOT', 'JOW', 'JOY', 'JUG', 'JUT', 'KAB', 'KAE', 'KAF', 'KAS', 'KAT', 
    'KEA', 'KEF', 'KEN', 'KEP', 'KID', 'KIF', 'KIN', 'KIP', 'KIT', 'KOA', 'KOB', 'KOI', 'KOP', 'KOR', 
    'KOS', 'KUE', 'LAB', 'LAC', 'LAD', 'LAG', 'LAM', 'LAP', 'LAR', 'LAS', 'LAT', 'LAV', 'LAW', 'LAX', 
    'LAY', 'LEA', 'LED', 'LEE', 'LEG', 'LEI', 'LET', 'LEU', 'LEV', 'LEX', 'LEY', 'LIB', 'LID', 'LIE', 
    'LIG', 'LIN', 'LIP', 'LIS', 'LIT', 'LOB', 'LOG', 'LOO', 'LOP', 'LOT', 'LOW', 'LOX', 'LUG', 'LUM', 
    'LUV', 'LUX', 'LYE', 'MAC', 'MAD', 'MAE', 'MAG', 'MAN', 'MAP', 'MAR', 'MAS', 'MAT', 'MAW', 'MAX', 
    'MAY', 'MED', 'MEE', 'MEG', 'MEL', 'MEN', 'MET', 'MEW', 'MHO', 'MIB', 'MID', 'MIG', 'MIL', 'MIM', 
    'MIR', 'MIS', 'MIX', 'MOB', 'MOD', 'MOG', 'MOL', 'MOM', 'MON', 'MOO', 'MOP', 'MOS', 'MOT', 'MOW', 
    'MUD', 'MUG', 'MUM', 'MUN', 'NAB', 'NAD', 'NAE', 'NAG', 'NAH', 'NAM', 'NAP', 'NAS', 'NAT', 'NAY', 
    'NEB', 'NED', 'NEE', 'NET', 'NEW', 'NIB', 'NIL', 'NIM', 'NIP', 'NIT', 'NOB', 'NOD', 'NOG', 'NOH', 
    'NOM', 'NON', 'NOR', 'NOS', 'NOT', 'NOW', 'NTH', 'NUB', 'NUN', 'NUS', 'NUT', 'OAF', 'OAK', 'OAR', 
    'OAT', 'OBA', 'OBE', 'OBI', 'OBO', 'OBS', 'OCA', 'ODA', 'ODE', 'ODS', 'OES', 'OFF', 'OFT', 'OHM', 
    'OHO', 'OHS', 'OIL', 'OIS', 'OKA', 'OKE', 'OLD', 'OLE', 'OMS', 'ONE', 'ONO', 'ONS', 'OOH', 'OPE', 
    'OPS', 'OPT', 'ORA', 'ORB', 'ORC', 'ORE', 'ORS', 'ORT', 'OUD', 'OUR', 'OUT', 'OVA', 'OWE', 'OWL', 
    'OWN', 'OXO', 'OXY', 'PAC', 'PAD', 'PAH', 'PAL', 'PAM', 'PAN', 'PAP', 'PAR', 'PAS', 'PAT', 'PAW', 
    'PAX', 'PAY', 'PEA', 'PEC', 'PED', 'PEE', 'PEG', 'PEH', 'PEN', 'PEP', 'PER', 'PES', 'PET', 'PEW', 
    'PHI', 'PHT', 'PIA', 'PIC', 'PIE', 'PIG', 'PIN', 'PIP', 'PIS', 'PIT', 'PIU', 'PIX', 'PLY', 'POH', 
    'POI', 'POL', 'POM', 'POO', 'POP', 'POS', 'POT', 'POW', 'POX', 'PRO', 'PRY', 'PUB', 'PUD', 'PUG', 
    'PUL', 'PUN', 'PUP', 'PUR', 'PUS', 'PUT', 'PYA', 'PYE', 'PYX', 'QAT', 'QIS', 'QUA', 'RAD', 'RAG', 
    'RAH', 'RAI', 'RAJ', 'RAM', 'RAN', 'RAP', 'RAS', 'RAT', 'RAW', 'RAX', 'RAY', 'REB', 'REC', 'RED', 
    'REE', 'REF', 'REG', 'REI', 'REM', 'REP', 'RES', 'RET', 'REV', 'REX', 'RHO', 'RIA', 'RIB', 'RID', 
    'RIG', 'RIM', 'RIN', 'RIP', 'ROB', 'ROC', 'ROD', 'ROE', 'ROM', 'ROT', 'ROW', 'RUB', 'RUE', 'RUG', 
    'RUM', 'RUN', 'RUT', 'RYA', 'RYE', 'SAC', 'SAD', 'SAE', 'SAG', 'SAL', 'SAP', 'SAT', 'SAU', 'SAV', 
    'SAW', 'SAX', 'SAY', 'SEA', 'SEC', 'SEE', 'SEG', 'SEL', 'SEN', 'SER', 'SET', 'SEW', 'SEX', 'SHA', 
    'SHE', 'SHH', 'SHY', 'SIB', 'SIN', 'SIP', 'SIS', 'SIT', 'SIX', 'SKA', 'SKI', 'SKY', 'SLY', 'SOB', 
    'SOD', 'SOL', 'SON', 'SOP', 'SOS', 'SOT', 'SOU', 'SOW', 'SOX', 'SOY', 'SPA', 'SPY', 'SUB', 'SUE', 
    'SUK', 'SUM', 'SUN', 'SUP', 'SUQ', 'TAB', 'TAD', 'TAE', 'TAG', 'TAJ', 'TAM', 'TAN', 'TAO', 'TAP', 
    'TAR', 'TAS', 'TAT', 'TAU', 'TAV', 'TAW', 'TAX', 'TEA', 'TED', 'TEE', 'TEG', 'TEL', 'TEN', 'TES', 
    'TET', 'TEW', 'THE', 'THO', 'THY', 'TIC', 'TIE', 'TIL', 'TIN', 'TIP', 'TIS', 'TIT', 'TOE', 'TOG', 
    'TOM', 'TON', 'TOO', 'TOP', 'TOR', 'TOT', 'TOW', 'TOY', 'TRY', 'TSK', 'TUB', 'TUG', 'TUI', 'TUM', 
    'TUN', 'TUP', 'TUT', 'TUX', 'TWO', 'UDO', 'UGH', 'UKE', 'ULM', 'UMP', 'UNI', 'URB', 'URD', 'URN', 
    'URP', 'USE', 'UTA', 'UTE', 'UTS', 'VAC', 'VAN', 'VAR', 'VAS', 'VAT', 'VAU', 'VAV', 'VAW', 'VEE', 
    'VEG', 'VET', 'VEX', 'VIA', 'VID', 'VIE', 'VIG', 'VIM', 'VIN', 'VIS', 'VOE', 'VOW', 'VOX', 'VUG', 
    'VUM', 'WAB', 'WAD', 'WAE', 'WAG', 'WAN', 'WAP', 'WAR', 'WAS', 'WAT', 'WAW', 'WAX', 'WAY', 'WEB', 
    'WED', 'WEE', 'WEM', 'WEN', 'WET', 'WEX', 'WEY', 'WHA', 'WHO', 'WHY', 'WIG', 'WIN', 'WIS', 'WIT', 
    'WIZ', 'WOE', 'WOG', 'WOK', 'WON', 'WOO', 'WOP', 'WOS', 'WOT', 'WOW', 'WRY', 'WUD', 'WUS', 'WYE', 
    'YAH', 'YAK', 'YAM', 'YAP', 'YAR', 'YAW', 'YAY', 'YEA', 'YEN', 'YEP', 'YES', 'YET', 'YEW', 'YID', 
    'YIN', 'YIP', 'YOB', 'YOD', 'YOK', 'YOM', 'YON', 'YOU', 'YOW', 'YUG', 'YUK', 'YUM', 'YUP', 'ZAG', 
    'ZAP', 'ZAS', 'ZAX', 'ZED', 'ZEE', 'ZEK', 'ZEL', 'ZEP', 'ZIG', 'ZIN', 'ZIP', 'ZIT', 'ZOA', 'ZOO'
  ]);
  